// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9c_-Kf1JzYwwCeSZek8mxIr6-yXZ6HQ',
    appId: '1:625158352702:web:092e27652e8271b6b5866f',
    messagingSenderId: '625158352702',
    projectId: 'expense-splitter-86259',
    authDomain: 'expense-splitter-86259.firebaseapp.com',
    storageBucket: 'expense-splitter-86259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC08V1pXKC1H32HcgURyECNC0Zr9xR9ZYE',
    appId: '1:625158352702:android:dc94ff3144dfa227b5866f',
    messagingSenderId: '625158352702',
    projectId: 'expense-splitter-86259',
    storageBucket: 'expense-splitter-86259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFi8gQeEcdram-S-lHcAKVB_qtKsMt0mk',
    appId: '1:625158352702:ios:28b59734ed7f78c6b5866f',
    messagingSenderId: '625158352702',
    projectId: 'expense-splitter-86259',
    storageBucket: 'expense-splitter-86259.firebasestorage.app',
    iosBundleId: 'com.visify.expenseSplitter',
  );
}
